version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "norwegian-dictionary"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-eo1vziaav18v"
s3_prefix = "norwegian-dictionary"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
