# Generated by Django 3.1.6 on 2021-02-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredTerm',
            fields=[
                ('term', models.TextField(primary_key=True, serialize=False)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Starred',
        ),
    ]
